from flask import Flask
from flask_restful import reqparse, abort, Api, Resource
# from model import make_sentence
from classifySneaker import classify


app = Flask(__name__)
api = Api(app)


parser = reqparse.RequestParser()
parser.add_argument('img')


class callSneakerClassifer(Resource):
    def post(self):
        """
        This function takes in some text that was past from the front end and gives
        it to the model. The model returns a new sentence and this returns that new
        sentence.

        Parameters
        ----------
        Resource: str
            A string containing a large ammount of text
        Returns
        -------
        str
            A new string generated by the model.
        """
        args = parser.parse_args()
        return classify(args['img'])


api.add_resource(callSneakerClassifer, '/img')


# use 4000 for when running other things locally
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=4000, debug=True) 